/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import java.text.*;
import java.util.Vector;

/**
 *
 * @author Quina Me Charopang
 * @author Abigayle Bonavente
 * @author Sean Calingangan
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPet = new javax.swing.JLabel();
        jTextFieldFName = new javax.swing.JTextField();
        jLabelOwnerGender = new javax.swing.JLabel();
        jTextFieldMinitial = new javax.swing.JTextField();
        jLabelMinitial = new javax.swing.JLabel();
        jTextFieldLName = new javax.swing.JTextField();
        jLabelLName = new javax.swing.JLabel();
        jLabelFname = new javax.swing.JLabel();
        jDateChooserOwnerBday = new com.toedter.calendar.JDateChooser();
        jComboBoxOwnerGender = new javax.swing.JComboBox<>();
        jLabelOwnerBday = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelMobileNo = new javax.swing.JLabel();
        jTextFieldMobileNo = new javax.swing.JTextField();
        jLabelOwner = new javax.swing.JLabel();
        jLabelSpecies = new javax.swing.JLabel();
        jTextFieldPetName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelPetName = new javax.swing.JLabel();
        jComboBoxPetGender = new javax.swing.JComboBox<>();
        jLabelPetGender = new javax.swing.JLabel();
        jLabelPetBday = new javax.swing.JLabel();
        jDateChooserPetBday = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePet = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOwner = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        jButtonDecline = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPet.setText("Pet Information");
        jPanel2.add(jLabelPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTextFieldFName.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldFName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFNameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 20));

        jLabelOwnerGender.setText("Gender");
        jPanel2.add(jLabelOwnerGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 20));

        jTextFieldMinitial.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldMinitial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldMinitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinitialActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMinitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 40, 20));

        jLabelMinitial.setText("Middle Initial");
        jPanel2.add(jLabelMinitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jTextFieldLName.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldLName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLNameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 160, 20));

        jLabelLName.setText("Last Name");
        jPanel2.add(jLabelLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabelFname.setText("First Name");
        jPanel2.add(jLabelFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jDateChooserOwnerBday.setDateFormatString("y M d");
        jPanel2.add(jDateChooserOwnerBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 170, -1));

        jComboBoxOwnerGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jComboBoxOwnerGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOwnerGenderActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxOwnerGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabelOwnerBday.setText("Birthday");
        jPanel2.add(jLabelOwnerBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, -1, 30));

        jTextFieldEmail.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 20));

        jLabelEmail.setText("Email");
        jPanel2.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabelMobileNo.setText("Mobile No.");
        jPanel2.add(jLabelMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jTextFieldMobileNo.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldMobileNo.setToolTipText("+639XXXXXXXXX \n");
        jTextFieldMobileNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMobileNoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, 20));

        jLabelOwner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOwner.setText("Owner Information");
        jPanel2.add(jLabelOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelSpecies.setText("Species");
        jPanel2.add(jLabelSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jTextFieldPetName.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPetName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPetNameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cat", "Dog" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 20));

        jLabelPetName.setText("Pet Name");
        jPanel2.add(jLabelPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jComboBoxPetGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel2.add(jComboBoxPetGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabelPetGender.setText("Gender");
        jPanel2.add(jLabelPetGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        jLabelPetBday.setText("Birthday");
        jPanel2.add(jLabelPetBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 20));

        jDateChooserPetBday.setDateFormatString("y M d");
        jPanel2.add(jDateChooserPetBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, -1));

        jTablePet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "name", "species", "gender", "birthdate", "owner_id"
            }
        ));
        jScrollPane1.setViewportView(jTablePet);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 730, 230));

        jTableOwner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "first_name", "middle_initial", "last_name", "age", "gender", "mobile_no", "email_address", "birthday", "address"
            }
        ));
        jScrollPane2.setViewportView(jTableOwner);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 730, 220));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 223, 750, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 710));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUpdate.setBackground(new java.awt.Color(153, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jButtonAdd.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAdd.setText("Insert / Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 0, 0));
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 100, 40));

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 30));

        jButtonAccept.setBackground(new java.awt.Color(102, 255, 102));
        jButtonAccept.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAccept.setText("Accept");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 40));

        jButtonDecline.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDecline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDecline.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDecline.setText("Decline");
        jButtonDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeclineActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDecline, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, 40));

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 120, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFNameActionPerformed

    private void jTextFieldMinitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinitialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinitialActionPerformed

    private void jTextFieldLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLNameActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobileNoActionPerformed

    private void jTextFieldPetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPetNameActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed
    private JFrame frame;
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?","AdminPanel", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jButtonDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeclineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeclineActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // this method resets or clears out all fields without modifying anything in the database.
        jTextFieldFName.setText("");
        jTextFieldLName.setText("");
        jTextFieldMinitial.setText("");
        jDateChooserOwnerBday.setDateFormatString("");
        jTextFieldEmail.setText("");
        jTextFieldMobileNo.setText("");
        jComboBoxOwnerGender.setSelectedItem("");   
        
        jTextFieldPetName.setText("");
        jComboBox1.setSelectedItem("");
        jComboBoxPetGender.setSelectedItem("");
        jDateChooserPetBday.setDateFormatString("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jComboBoxOwnerGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOwnerGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOwnerGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDecline;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxOwnerGender;
    private javax.swing.JComboBox<String> jComboBoxPetGender;
    private com.toedter.calendar.JDateChooser jDateChooserOwnerBday;
    private com.toedter.calendar.JDateChooser jDateChooserPetBday;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelLName;
    private javax.swing.JLabel jLabelMinitial;
    private javax.swing.JLabel jLabelMobileNo;
    private javax.swing.JLabel jLabelOwner;
    private javax.swing.JLabel jLabelOwnerBday;
    private javax.swing.JLabel jLabelOwnerGender;
    private javax.swing.JLabel jLabelPet;
    private javax.swing.JLabel jLabelPetBday;
    private javax.swing.JLabel jLabelPetGender;
    private javax.swing.JLabel jLabelPetName;
    private javax.swing.JLabel jLabelSpecies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableOwner;
    private javax.swing.JTable jTablePet;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldLName;
    private javax.swing.JTextField jTextFieldMinitial;
    private javax.swing.JTextField jTextFieldMobileNo;
    private javax.swing.JTextField jTextFieldPetName;
    // End of variables declaration//GEN-END:variables
}
